name: Deploy to Surge

on:
  push:
    branches:
      - main
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run:  # Este paso es opcional, si tienes dependencias de Node.js

    - name: Install Surge and Deploy
      run: |

        npm install --global surge

        surge token ${{ secrets.SURGE_TOKEN }}
         surge --project ./src --domain gallagher-primerp.surge.sh

